# Generated by Django 5.2.16 on 2026-07-29 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('meaning', models.CharField(max_length=40)),
                ('copy_text', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(blank=True, max_length=160)),
                ('prompt', models.TextField(blank=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('candidates', models.ManyToManyField(blank=True, related_name='candidate_for_emoji_items', to='assets.assetversion')),
                ('selected_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_emoji_items', to='assets.assetversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnimationSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loop_count', models.PositiveSmallIntegerField(default=0, help_text='0 表示无限循环')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('output_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animation_sequence_outputs', to='assets.assetversion')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animation_sequence', to='emoji.emojiitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmojiPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('pack_type', models.CharField(choices=[('album', '表情专辑'), ('single', '表情单品')], default='album', max_length=12)),
                ('media_type', models.CharField(choices=[('static', '静态 PNG'), ('dynamic', '动态 GIF')], default='static', max_length=12)),
                ('target_count', models.PositiveSmallIntegerField(default=8)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('brief_approved', 'Brief 已确认'), ('generating', '生成中'), ('creative_review', '创意审稿'), ('processing', '素材处理中'), ('qa_review', '质量与合规审核'), ('export_ready', '可导出'), ('submitted', '已投稿'), ('published', '已上架'), ('rework', '返修中'), ('archived', '已归档')], default='draft', max_length=24)),
                ('audience', models.CharField(blank=True, max_length=160)),
                ('tone', models.CharField(blank=True, max_length=160)),
                ('creative_brief', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('banner_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_for_packs', to='assets.assetversion')),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_packs', to='assets.assetversion')),
                ('icon_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon_for_packs', to='assets.assetversion')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_emoji_packs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_packs', to='core.creativeproject')),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emoji_packs', to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='emojiitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='emoji.emojipack'),
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(max_length=40)),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '退回')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emoji_approval_records', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='emoji.emojipack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_bundles', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_bundles', to='assets.assetversion')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='emoji.emojipack')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_on', models.DateField()),
                ('source', models.CharField(default='manual', max_length=120)),
                ('metrics', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metric_snapshots', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='emoji.emojipack')),
                ('source_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_snapshots', to='assets.assetversion')),
            ],
            options={
                'ordering': ['-captured_on'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('version', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=120)),
                ('template', models.TextField()),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code', '-version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='unique_prompt_template_version')],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('plan', '语义策划'), ('image', '图像生成'), ('frame', '序列帧生成'), ('assemble', '动图合成'), ('export', '投稿包导出')], max_length=20)),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt', models.TextField(blank=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('succeeded', '已完成'), ('failed', '失败'), ('blocked', '等待外部配置'), ('cancelled', '已取消')], default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('external_job_id', models.CharField(blank=True, max_length=160)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='emoji.emojiitem')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='emoji.emojipack')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='emoji.prompttemplateversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('in_review', '审核中'), ('rejected', '已驳回'), ('approved', '审核通过'), ('published', '已上架')], default='submitted', max_length=16)),
                ('platform_work_id', models.CharField(blank=True, max_length=120)),
                ('submitted_at', models.DateTimeField()),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('export_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='emoji.exportbundle')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='emoji.emojipack')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emoji_submission_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passed', models.BooleanField(default=False)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_validation_runs', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='emoji.emojipack')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('error', '错误'), ('warning', '警告')], max_length=12)),
                ('message', models.CharField(max_length=300)),
                ('remediation', models.CharField(blank=True, max_length=300)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_issues', to='assets.assetversion')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='emoji.emojiitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='emoji.validationrun')),
            ],
            options={
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AnimationFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(default=120)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animation_frames', to='assets.assetversion')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='emoji.animationsequence')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('sequence', 'order'), name='unique_sequence_frame_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='emojiitem',
            constraint=models.UniqueConstraint(fields=('pack', 'order'), name='unique_pack_item_order'),
        ),
        migrations.AddConstraint(
            model_name='metricsnapshot',
            constraint=models.UniqueConstraint(fields=('pack', 'captured_on', 'source'), name='unique_pack_metric_snapshot'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['status', 'job_type', '-created_at'], name='emoji_gener_status_83270f_idx'),
        ),
    ]
