# Generated by Django 5.2.16 on 2026-07-29 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='job_type',
            field=models.CharField(choices=[('plan', '语义策划'), ('prompt', '提示词优化'), ('image', '图像生成'), ('frame', '序列帧生成'), ('assemble', '动图合成'), ('export', '投稿包导出')], max_length=20),
        ),
        migrations.CreateModel(
            name='PromptPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('base', '基础'), ('style', '风格'), ('composition', '构图'), ('quality', '质量'), ('negative', '负向')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('content', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompt_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='emojipack',
            name='prompt_presets',
            field=models.ManyToManyField(blank=True, related_name='emoji_packs', to='emoji.promptpreset'),
        ),
        migrations.AddConstraint(
            model_name='promptpreset',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_prompt_preset_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='promptpreset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('category',), name='unique_default_prompt_preset_per_category'),
        ),
    ]
