# Generated by Django 5.2.16 on 2026-07-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0002_alter_generationjob_job_type_promptpreset_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promptpreset',
            name='unique_default_prompt_preset_per_category',
        ),
    ]
