# Generated by Django 5.2.16 on 2026-07-29 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('active', '已启用'), ('planned', '筹备中'), ('paused', '已暂停')], default='planned', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('adapter_path', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IPCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPCharacterVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('personality', models.TextField(blank=True)),
                ('style_anchors', models.JSONField(blank=True, default=list)),
                ('forbidden_elements', models.JSONField(blank=True, default=list)),
                ('palette', models.JSONField(blank=True, default=list)),
                ('reference_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.ipcharacter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_character_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['character__name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TransitionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.UUIDField()),
                ('from_state', models.CharField(blank=True, max_length=40)),
                ('to_state', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_transition_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('source_snapshot', models.TextField(blank=True)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('lane', models.CharField(choices=[('ip', '原创 IP'), ('trend', '热点快线'), ('hybrid', 'IP × 热点')], default='ip', max_length=12)),
                ('status', models.CharField(choices=[('active', '生产中'), ('paused', '已暂停'), ('completed', '已完成'), ('archived', '已归档')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_creative_projects', to=settings.AUTH_USER_MODEL)),
                ('character_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.ipcharacterversion')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.productline')),
                ('trend_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.trendtopic')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ipcharacterversion',
            constraint=models.UniqueConstraint(fields=('character', 'version'), name='unique_character_version'),
        ),
        migrations.AddIndex(
            model_name='transitionevent',
            index=models.Index(fields=['object_type', 'object_id', '-created_at'], name='core_transi_object__66b283_idx'),
        ),
    ]
