# Generated by Django 5.2.16 on 2026-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeproject',
            name='lane',
            field=models.CharField(choices=[('ip', '原创 IP'), ('trend', '热点快线'), ('hybrid', 'IP × 热点'), ('product', '产品研发')], default='ip', max_length=12),
        ),
    ]
