# Generated by Django 5.2.16 on 2026-07-29 15:46

import apps.assets.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.assets.models.asset_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('source', '源素材'), ('reference', '角色参考图'), ('candidate', '生成候选'), ('final_static', '静态成品'), ('animation_frame', '序列帧'), ('final_gif', '动态成品'), ('cover', '专辑封面'), ('icon', '聊天图标'), ('banner', '详情横幅'), ('export', '导出包')], max_length=24)),
                ('source', models.CharField(choices=[('upload', '人工上传'), ('local', '本地演示'), ('openai', 'OpenAI'), ('processor', '媒体处理器'), ('exporter', '导出器')], default='upload', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('frame_count', models.PositiveIntegerField(default=1)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_versions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='assets.assetversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(default='wechat', max_length=40)),
                ('product_type', models.CharField(max_length=40)),
                ('media_type', models.CharField(blank=True, max_length=20)),
                ('version', models.CharField(max_length=40)),
                ('effective_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True)),
                ('constraints', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'product_type', 'media_type', 'version'), name='unique_platform_ruleset_version')],
            },
        ),
        migrations.CreateModel(
            name='RightsEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('original', '原创声明'), ('authorization', '版权授权'), ('portrait', '肖像授权'), ('trademark', '商标证明'), ('other', '其他')], max_length=20)),
                ('rights_owner', models.CharField(max_length=160)),
                ('proof_file', models.FileField(blank=True, upload_to=apps.assets.models.proof_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'zip'])])),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights_evidence', to='assets.assetversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rights_evidence', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_evidence', to='core.creativeproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
