# Generated by Django 5.2.16 on 2026-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetversion',
            name='kind',
            field=models.CharField(choices=[('source', '源素材'), ('reference', '角色参考图'), ('candidate', '生成候选'), ('final_static', '静态成品'), ('animation_frame', '序列帧'), ('final_gif', '动态成品'), ('cover', '专辑封面'), ('icon', '聊天图标'), ('banner', '详情横幅'), ('red_packet_cover', '红包封面成品'), ('red_packet_preview', '红包封面预览'), ('build_package', '小程序构建包'), ('experience_qr', '小程序体验码'), ('screenshot', '小程序截图'), ('document', '业务文档'), ('export', '导出包')], max_length=24),
        ),
    ]
