# Generated by Django 5.2.16 on 2026-07-29 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_assetversion_kind'),
        ('core', '0002_alter_creativeproject_lane'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProgramRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('app_id', models.CharField(blank=True, max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('release_type', models.CharField(choices=[('feature', '功能版本'), ('hotfix', '紧急修复'), ('initial', '首次发布')], default='feature', max_length=12)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('prd_approved', 'PRD 已确认'), ('developing', '开发中'), ('build_ready', '构建已就绪'), ('experience_review', '体验版验收'), ('compliance_review', '隐私与合规审核'), ('qa_review', '发布 QA'), ('export_ready', '审核包可导出'), ('submitted', '已提交微信审核'), ('approved', '微信审核通过'), ('released', '已发布'), ('rework', '返修中'), ('archived', '已归档')], default='draft', max_length=24)),
                ('prd_summary', models.TextField(blank=True)),
                ('change_log', models.TextField(blank=True)),
                ('privacy_summary', models.TextField(blank=True)),
                ('service_category', models.CharField(blank=True, max_length=120)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_mini_program_releases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_program_releases', to='core.creativeproject')),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mini_program_releases', to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramExportBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mini_program_exports', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_program_exports', to='assets.assetversion')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.platformruleset')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='miniprogram.miniprogramrelease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('prd', '产品范围'), ('build', '构建配置'), ('functional', '功能验收'), ('privacy', '隐私合规'), ('security', '安全检查'), ('platform', '微信平台资料')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('evidence_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_checklist_evidence', to='assets.assetversion')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='miniprogram.miniprogramrelease')),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('build_package', '构建包'), ('experience_qr', '体验二维码'), ('screenshot', '页面截图'), ('privacy_document', '隐私说明'), ('test_evidence', '测试证据')], max_length=24)),
                ('label', models.CharField(max_length=120)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_program_artifacts', to='assets.assetversion')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='miniprogram.miniprogramrelease')),
            ],
            options={
                'ordering': ['artifact_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(max_length=40)),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '退回')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_approval_records', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='miniprogram.miniprogramrelease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('in_review', '审核中'), ('rejected', '已驳回'), ('approved', '审核通过'), ('released', '已发布')], default='submitted', max_length=16)),
                ('platform_audit_id', models.CharField(blank=True, max_length=120)),
                ('submitted_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('export_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='miniprogram.miniprogramexportbundle')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='miniprogram.miniprogramrelease')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('steps', models.JSONField(default=list)),
                ('expected_result', models.TextField()),
                ('actual_result', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('pending', '待执行'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞')], default='pending', max_length=12)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_program_test_evidence', to='assets.assetversion')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_mini_program_tests', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='miniprogram.miniprogramrelease')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passed', models.BooleanField(default=False)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mini_program_validations', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='miniprogram.miniprogramrelease')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniProgramValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('error', '错误'), ('warning', '警告')], max_length=12)),
                ('message', models.CharField(max_length=300)),
                ('remediation', models.CharField(blank=True, max_length=300)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='miniprogram.miniprogramvalidationrun')),
            ],
            options={
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='miniprogramrelease',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_project_mini_program_version'),
        ),
        migrations.AddConstraint(
            model_name='miniprogramchecklistitem',
            constraint=models.UniqueConstraint(fields=('release', 'category', 'title'), name='unique_mini_program_checklist_item'),
        ),
        migrations.AddConstraint(
            model_name='miniprogramtestcase',
            constraint=models.UniqueConstraint(fields=('release', 'name'), name='unique_mini_program_test_case'),
        ),
    ]
