# Generated by Django 5.2.16 on 2026-07-29 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_assetversion_kind'),
        ('core', '0002_alter_creativeproject_lane'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedPacketCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, max_length=160)),
                ('cover_story', models.TextField(blank=True)),
                ('greeting', models.CharField(blank=True, max_length=120)),
                ('style_keywords', models.JSONField(blank=True, default=list)),
                ('design_target', models.PositiveSmallIntegerField(default=3)),
                ('planned_quantity', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('brief_approved', 'Brief 已确认'), ('designing', '封面设计中'), ('creative_review', '创意审稿'), ('rights_review', '权利材料审核'), ('qa_review', '质量与合规审核'), ('export_ready', '可导出'), ('submitted', '已提交微信审核'), ('approved', '微信审核通过'), ('distributing', '发放中'), ('completed', '发放完成'), ('rework', '返修中'), ('archived', '已归档')], default='draft', max_length=24)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_red_packet_campaigns', to=settings.AUTH_USER_MODEL)),
                ('preview_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_packet_previews', to='assets.assetversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_packet_campaigns', to='core.creativeproject')),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_packet_campaigns', to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(max_length=40)),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '退回')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_packet_approval_records', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='redpacket.redpacketcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketExportBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='redpacket.redpacketcampaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_red_packet_exports', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_packet_exports', to='assets.assetversion')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_order_no', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('planned', '待下单'), ('purchased', '已下单'), ('available', '可发放'), ('exhausted', '已用完'), ('cancelled', '已取消')], default='planned', max_length=16)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='redpacket.redpacketcampaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_red_packet_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('distributed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_red_packet_distributions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='redpacket.redpacketorder')),
            ],
            options={
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('in_review', '审核中'), ('rejected', '已驳回'), ('approved', '审核通过')], default='submitted', max_length=16)),
                ('platform_work_id', models.CharField(blank=True, max_length=120)),
                ('submitted_at', models.DateTimeField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='redpacket.redpacketcampaign')),
                ('export_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='redpacket.redpacketexportbundle')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_packet_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passed', models.BooleanField(default=False)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='redpacket.redpacketcampaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_red_packet_validations', to=settings.AUTH_USER_MODEL)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.platformruleset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('error', '错误'), ('warning', '警告')], max_length=12)),
                ('message', models.CharField(max_length=300)),
                ('remediation', models.CharField(blank=True, max_length=300)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='redpacket.redpacketvalidationrun')),
            ],
            options={
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RedPacketDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('prompt', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('review_note', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_packet_designs', to='assets.assetversion')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='redpacket.redpacketcampaign')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'order'), name='unique_red_packet_design_order'), models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('campaign',), name='single_selected_red_packet_design')],
            },
        ),
    ]
